apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ew3lp3ubr-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ew3lp3ubr-java-springboot-gitops