apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ew3lp3ubr-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b99c4a57e0.clc8.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:15831621e1d08d5ea4959318ce7287128b8d111b@sha256:c0385726c10ad9f68ac7d360193b7d49460abd32d4f8e02587e24081f0cbbf92
          name: container-image
